### ISSUE TITLE
Upstream status of the patch

### ISSUE THREAD

**Issue by mr-nice** [Blinkinlabs/OpenOCD#1]
Hi all,
what is the upstream status of your patch for OpenOCD? Is there anything which blocks it?

**Comment by cibomahto** [comment]
Hi- I apologize that I haven't made it through all of the steps required to actually send the patch. It ended up being a bit more work than I imagined, since I haven't used any of their tools before. I'll try to get fully registered so I can submit it.

For reference, here's the merge guide: http://openocd.org/doc/doxygen/html/patchguide.html

**Comment by mr-nice** [comment]
Cool, thanks for the effort! Wow, that indeed looks like quite an effort to submit patches.

**Comment by cibomahto** [comment]
Ok, all submitted:
http://openocd.zylin.com/#/c/6371/
http://openocd.zylin.com/#/c/6372/

**Comment by cibomahto** [comment]
The changes are merged, and upstream OpenOCD now has a ' jtag_hat_rpi2.cfg' interface script as well.
